In [2]:
import numpy as np

def add_padding(image, padding):
    """Add padding to the input image."""
    if padding > 0:
        return np.pad(image, pad_width=padding, mode='constant', constant_values=0)
    return image

def convolve(image, kernel, stride):
    """Perform convolution on the input image using the given kernel."""
    output_dim = (image.shape[0] - kernel.shape[0]) // stride + 1
    conv_output = np.zeros((output_dim, output_dim))
    
    for i in range(output_dim):
        for j in range(output_dim):
            region = image[i * stride:i * stride + kernel.shape[0], j * stride:j * stride + kernel.shape[1]]
            conv_output[i, j] = np.sum(region * kernel)
    
    return conv_output

def relu(x):
    """Apply ReLU activation function."""
    return np.maximum(0, x)

def max_pooling(image, pool_size, stride):
    """Perform max pooling on the input image."""
    pooled_dim = (image.shape[0] - pool_size) // stride + 1
    pooled_output = np.zeros((pooled_dim, pooled_dim))
    
    for i in range(pooled_dim):
        for j in range(pooled_dim):
            region = image[i * stride:i * stride + pool_size, j * stride:j * stride + pool_size]
            pooled_output[i, j] = np.max(region)
    
    return pooled_output

def flatten(image):
    """Flatten the image into a 1D array."""
    return image.flatten()

def sigmoid(x):
    """Apply sigmoid activation function."""
    return 1 / (1 + np.exp(-x))

# Main execution
if __name__ == "__main__":
    # Define the input image (4x4 matrix) and kernel (2x2)
    input_image = np.array([
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12],
        [13, 14, 15, 16]
    ])
    kernel = np.array([
        [1, 0],
        [0, -1]
    ])
    
    # Parameters
    stride = 1
    padding = 0
    pool_size = 2

    # Forward propagation
    padded_image = add_padding(input_image, padding)
    conv_output = convolve(padded_image, kernel, stride)
    relu_output = relu(conv_output)
    pooled_output = max_pooling(relu_output, pool_size, stride=pool_size)
    flattened_output = flatten(pooled_output)
    final_output = sigmoid(flattened_output)

    # Print results
    print("Input Image:\n", input_image)
    print("Padded Image:\n", padded_image)
    print("Convolution Output:\n", conv_output)
    print("ReLU Output:\n", relu_output)
    print("Pooled Output:\n", pooled_output)
    print("Flattened Output:\n", flattened_output)
    print("Final Output (Sigmoid):\n", final_output)


Input Image:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Padded Image:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Convolution Output:
 [[-5. -5. -5.]
 [-5. -5. -5.]
 [-5. -5. -5.]]
ReLU Output:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Pooled Output:
 [[0.]]
Flattened Output:
 [0.]
Final Output (Sigmoid):
 [0.5]
